/*

 * File: app/store/Aula.js

 *

 * This file was generated by Sencha Architect version 2.1.0.

 * http://www.sencha.com/products/architect/

 *

 * This file requires use of the Ext JS 4.1.x library, under independent license.

 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more

 * details see http://www.sencha.com/license or contact license@sencha.com.

 *

 * This file will be auto-generated each and everytime you save your project.

 *

 * Do NOT hand edit this file.

 */



Ext.define('vision.store.Aula', {

    extend: 'Ext.data.Store',



    requires: [

        'vision.model.Aula'

    ],



    constructor: function(cfg) {

        var me = this;

        cfg = cfg || {};

        me.callParent([Ext.apply({

            storeId: 'Aula',

            model: 'vision.model.Aula',

            data: [{cod_fia_amb: '1',tipo:'Aula',value: '01-0101'},

			{cod_fia_amb: '2',tipo:'Aula',value: '01-0102'},

			{cod_fia_amb: '3',tipo:'Aula',value: '01-0103'},

			{cod_fia_amb: '4',tipo:'Aula',value: '01-0104'},

			{cod_fia_amb: '5',tipo:'Aula',value: '01-0201'},

			{cod_fia_amb: '6',tipo:'Aula',value: '01-0202'},

			{cod_fia_amb: '7',tipo:'Aula',value: '01-0203'},

			{cod_fia_amb: '8',tipo:'Aula',value: '01-0204'},

			{cod_fia_amb: '9',tipo:'Aula',value: '01-0301'},

			{cod_fia_amb: '10',tipo:'Aula',value: '01-0302'},

			{cod_fia_amb: '11',tipo:'Aula',value: '01-0303'},

			{cod_fia_amb: '12',tipo:'Aula',value: '01-0304'},

			{cod_fia_amb: '13',tipo:'Aula',value: '03-0101'},

			{cod_fia_amb: '14',tipo:'Aula',value: '03-0102'},

			{cod_fia_amb: '15',tipo:'Aula',value: '03-0103'},

			{cod_fia_amb: '16',tipo:'Aula',value: '03-0104'},

			{cod_fia_amb: '17',tipo:'Aula',value: '03-0105'},

			{cod_fia_amb: '18',tipo:'Aula',value: '03-0201'},

			{cod_fia_amb: '19',tipo:'Aula',value: '03-0202'},

			{cod_fia_amb: '20',tipo:'Aula',value: '03-0203'},

			{cod_fia_amb: '21',tipo:'Aula',value: '03-0204'},

			{cod_fia_amb: '22',tipo:'Aula',value: '03-0205'},

			{cod_fia_amb: '23',tipo:'Aula',value: '03-0304'},

			{cod_fia_amb: '24',tipo:'Aula',value: '03-0302'},

			{cod_fia_amb: '25',tipo:'Aula',value: '03-0303'},

			{cod_fia_amb: '26',tipo:'Aula',value: '03-0304'},

			{cod_fia_amb: '27',tipo:'Aula',value: '03-0305'},

			{cod_fia_amb: '28',tipo:'Laboratorio',value: '02-0A-1'},

			{cod_fia_amb: '29',tipo:'Laboratorio',value: '02-0B-1'},

			{cod_fia_amb: '30',tipo:'Laboratorio',value: '02-0C-1'},

			{cod_fia_amb: '31',tipo:'Laboratorio',value: '02-0A-2'},

			{cod_fia_amb: '32',tipo:'Laboratorio',value: '02-0B-2'},

			{cod_fia_amb: '33',tipo:'Laboratorio',value: '02-0C-2'},

			{cod_fia_amb: '34',tipo:'Laboratorio',value: '02-0A-3'},

			{cod_fia_amb: '35',tipo:'Laboratorio',value: '02-0B-3'},

			{cod_fia_amb: '36',tipo:'Laboratorio',value: '02-0C-3'},

			{cod_fia_amb: '37',tipo:'Coliseo',value: 'CO-1'},

			{cod_fia_amb: '38',tipo:'Coliseo',value: 'CO-2'},

			{cod_fia_amb: '39',tipo:'Coliseo',value: 'CO-3'}

            ],

            proxy: {

                type: 'ajax',

                reader: {

                    type: 'json'

                }

            }

        }, cfg)]);

    }

});