/*
 * File: app/store/Aula.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('vision.store.Aula', {
    extend: 'Ext.data.Store',

    requires: [
        'vision.model.Aula'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyJsonStore2',
            model: 'vision.model.Aula',
            data: [
                {
                    cod_fia_amb: '1',
                    value: '101'
                },
                {
                    cod_fia_amb: '2',
                    value: '102'
                },
                {
                    cod_fia_amb: '3',
                    value: '103'
                }
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});