/*

 * File: app/view/Contenedor.js

 *

 * This file was generated by Sencha Architect version 2.1.0.

 * http://www.sencha.com/products/architect/

 *

 * This file requires use of the Ext JS 4.1.x library, under independent license.

 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more

 * details see http://www.sencha.com/license or contact license@sencha.com.

 *

 * This file will be auto-generated each and everytime you save your project.

 *

 * Do NOT hand edit this file.

 */



Ext.define('vision.view.Contenedor', {

    extend: 'Ext.panel.Panel',

    alias: 'widget.contenedor',



    requires: [

        'vision.view.PanelPrincipal'

    ],



    height: 250,

    width: 400,

    layout: {

        type: 'border'

    },



    initComponent: function() {

        var me = this;



        Ext.applyIf(me, {

            dockedItems: [

                {

                    xtype: 'toolbar',

                    dock: 'top',

                    items: [

                        {

                            xtype: 'container',

                            height: 70,

                            width: 250,

                            items: [

                                {

                                    xtype: 'container',

                                    cls: 'icon-logo',

                                    height: 45

                                },

                                {

                                    xtype: 'label',

                                    margin: '0 0 0 20',

                                    style: 'color:#4F279B;',

                                    styleHtmlContent: true,

                                    text: 'Sistema de gestion de eventos FIA.'

                                }

                            ]

                        },

                        {

                            xtype: 'tbseparator'

                        },

                        {

                            xtype: 'tbfill'

                        },

                        {

                            xtype: 'tbseparator'

                        },

                        {

                            xtype: 'container',

                            margin: '0 5 0 5',

                            layout: {

                                align: 'stretch',

                                type: 'vbox'

                            },

                            items: [

                                {

                                    xtype: 'label',

                                    html: '<p align="right" class="text-morado">Bienvenido: Juan Palermo<p>',

                                    id: 'userlabel'

                                },

                                {

                                    xtype: 'label',

                                    id: 'lbHora'

                                }

                            ]

                        }

                    ]

                },

                {

                    xtype: 'toolbar',

                    dock: 'top',

                    items: [

                        {

                            xtype: 'button',

                            handler: function(button, event) {

                                var panelp=Ext.getCmp('panelprincipal');

                                Ext.getCmp('viewPanel').layout.setActiveItem(panelp);



                            },

                            itemId: 'btnPrincipal',

                            iconCls: 'icon-history',

                            scale: 'medium',

                            text: 'Inicio'

                        },

                        {

                            xtype: 'tbseparator'

                        },

                        {

                            xtype: 'button',

                            handler: function(button, event) {

                                var grid=Ext.getCmp('gridponencia');


                                if(!grid){

                                    Ext.create('vision.view.GridPonencia');

                                grid=Ext.getCmp('gridponencia');}


                                Ext.getCmp('viewPanel').layout.setActiveItem(grid);




                            },

                            itemId: 'btnMponencia',

                            iconCls: 'icon-pago',

                            scale: 'medium',

                            text: 'Mantener Ponencia'

                        },

                        {

                            xtype: 'tbseparator'

                        },

                        {

                            xtype: 'button',

                            handler: function(button, event) {

                                var grid=Ext.getCmp('gridEvento');


                                if(!grid){

                                    Ext.create('vision.view.GridEvento');

                                grid=Ext.getCmp('gridEvento');}


                                Ext.getCmp('viewPanel').layout.setActiveItem(grid);



                            },

                            iconCls: 'icon-add-event',

                            scale: 'medium',

                            text: 'Mantener Evento'

                        },

                        {

                            xtype: 'tbseparator'

                        },

                        {

                            xtype: 'button',

                            handler: function(button, event) {

                                var grid=Ext.getCmp('gridExpositor');


                                if(!grid){

                                    Ext.create('vision.view.GridExpositor');

                                grid=Ext.getCmp('gridExpositor');}


                                Ext.getCmp('viewPanel').layout.setActiveItem(grid);

                            },

                            scale: 'large',

                            text: 'Mantener Expositor'

                        },

                        {

                            xtype: 'tbfill'

                        },

                        {

                            xtype: 'tbspacer'

                        },

                        {

                            xtype: 'button',

                            id: 'btnUser',

                            itemId: 'usuario',

                            iconCls: 'icon-admin',

                            scale: 'medium',

                            text: 'Usuario'

                        },

                        {

                            xtype: 'tbspacer'

                        },

                        {

                            xtype: 'button',

                            handler: function(button, event) {

                                window.location.href='http://sysmov.net/sge/seguridad/login/logout';

                            },

                            iconCls: 'icon-logout',

                            scale: 'medium',

                            text: 'Salir'

                        }

                    ]

                }

            ],

            items: [

                {

                    xtype: 'panel',

                    region: 'center',

                    border: 0,

                    id: 'viewPanel',

                    margin: '5 5 5 5',

                    layout: {

                        type: 'card'

                    },

                    items: [

                        {

                            xtype: 'panelPrincipal'

                        }

                    ]

                }

            ]

        });



        me.callParent(arguments);

    }



});