/*
 * File: app/view/GridExpositor.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('vision.view.GridExpositor', {
    extend: 'Ext.grid.Panel',

    height: 300,
    id: 'gridExpositor',
    itemId: 'gridExpositor',
    title: 'Mantener Expositor',
    columnLines: false,
    store: 'Expositor',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'rownumberer'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: false,
                    width: 120,
                    defaultWidth: 120,
                    align: 'center',
                    dataIndex: 'cod_exp',
                    text: 'Codigo de Expositor'
                },
                {
                    xtype: 'gridcolumn',
                    width: 220,
                    defaultWidth: 200,
                    dataIndex: 'tip_doc',
                    text: 'Tipo Documento'
                },
                {
                    xtype: 'gridcolumn',
                    width: 200,
                    defaultWidth: 220,
                    dataIndex: 'num_doc',
                    text: 'Num. documento'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'nom',
                    text: 'Nombre'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'pais_exp',
                    text: 'Pais'
                }
            ],
            viewConfig: {

            },
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    afterPageText: 'de {0}',
                    beforePageText: 'Pagina',
                    displayInfo: true,
                    displayMsg: 'Expositores {0} - {1} de {2}',
                    emptyMsg: 'No Existen Expositores',
                    firstText: 'Primera Pagina',
                    lastText: 'Ultima Pagina',
                    prevText: 'Pagina Anterior',
                    refreshText: 'Actualizar',
                    store: 'Expositor'
                },
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var winp=Ext.getCmp('winExpositor');

                                if(!winp){
                                    Ext.create('vision.view.MantenerExpositor');
                                winp=Ext.getCmp('winExpositor');}

                                //Ext.getCmp('cod_exp_pon').setDisabled(false);
                                Ext.getCmp('formExpositor').getForm().reset(); 
                                winp.show();
                            },
                            id: 'btnRegExpo',
                            iconCls: 'icon-add',
                            text: 'Registrar Expositor'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {


                                var winp=Ext.getCmp('winExpositor');

                                if(!winp){
                                    Ext.create('vision.view.MantenerExpositor');
                                winp=Ext.getCmp('winExpositor');}
                                var cod_exp=sessionStorage.getItem('cod_exp');
                                if(cod_exp!='-1'){
                                    //Ext.getCmp('cod_exp_pon').setDisabled(true);
                                    var record=Ext.getCmp('gridExpositor').getStore().findRecord('cod_exp',cod_exp);
                                    Ext.getCmp('cod_exp').setValue(record.get('cod_exp'));
                                    Ext.getCmp('tip_doc').setValue(record.get('tip_doc'));
                                    Ext.getCmp('num_doc').setValue(record.get('num_doc'));
                                    Ext.getCmp('nom_exp').setValue(record.get('nom_exp'));
                                    Ext.getCmp('ape_pat_exp').setValue(record.get('ape_pat_exp'));
                                    Ext.getCmp('ape_mat_exp').setValue(record.get('ape_mat_exp'));
                                    Ext.getCmp('pais_exp').setValue(record.get('pais_exp'));

                                    // Ext.getCmp('id_req_pon').setValue(record.get('id_req_pon'));
                                    winp.show();



                                }else Ext.Msg.alert('Precaución','Debe seleccionar una ponencia.');



                            },
                            id: 'btnManExpo',
                            iconCls: 'icon-edit',
                            text: 'Modificar Expositor'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {

                                var cod_exp=sessionStorage.getItem('cod_exp');
                                if(cod_exp!=-1){
                                    var sexpositor=Ext.getCmp('gridExpositor').getStore();
                                    var record=Ext.getCmp('gridExpositor').getStore().findRecord('cod_exp',cod_exp);
                                    var opt=Ext.MessageBox.confirm('Comfirmar', 'Esta se guro que desea eliminar el:<br>Expositor: <b>'+record.get('nom')+'</b><br>Codigo: <b>'+cod_exp+'<b>',
                                    function(button) {
                                        if (button === 'yes') {
                                            sexpositor.load({
                                                url:'../../administracion/expositor/borrar_expositor',
                                                method: 'POST',
                                                params:{'tipoSql':'delete','cod_exp':cod_exp},
                                                scope: this,
                                                callback: function(records, operation, success,response) {
                                                    // the operation object
                                                    // contains all of the details of the load operation
                                                    //this.load();

                                                }

                                            });
                                        }//END if

                                    });
                                }else Ext.Msg.alert('Precaución','Debe seleccionar una ponencia.');

                            },
                            text: 'Eliminar Expositor'
                        }
                    ]
                }
            ],
            listeners: {
                select: {
                    fn: me.onGridponenciaSelect,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onGridponenciaSelect: function(selModel, record, index, options) {
        sessionStorage.setItem('cod_exp',record.get('cod_exp'));
    }

});