/*

 * File: app/view/MantenerEvento.js

 *

 * This file was generated by Sencha Architect version 2.1.0.

 * http://www.sencha.com/products/architect/

 *

 * This file requires use of the Ext JS 4.1.x library, under independent license.

 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more

 * details see http://www.sencha.com/license or contact license@sencha.com.

 *

 * This file will be auto-generated each and everytime you save your project.

 *

 * Do NOT hand edit this file.

 */



Ext.define('vision.view.MantenerEvento', {

    extend: 'Ext.window.Window',



    requires: [

        'vision.view.override.MantenerEvento'

    ],



    height: 290,

    id: 'winEvento',

    width: 455,

    layout: {

        type: 'border'

    },

    title: 'Mantener Evento',

    animateTarget: 'btn_CEvento',

    modal: true,



    initComponent: function() {

        var me = this;



        Ext.applyIf(me, {

            items: [

                {

                    xtype: 'form',

                    region: 'center',

                    border: 0,

                    id: 'formEvento',

                    bodyPadding: 10,

                    url: '../../administracion/evento/registar_evento',

                    waitTitle: 'Guardando...',

                    items: [

                        {

                            xtype: 'fieldset',

                            title: 'Datos de Evento',

                            items: [

                                {

                                    xtype: 'textfield',

                                    anchor: '100%',

                                    cls: 'x-item-disabled',

                                    hidden: false,

                                    id: 'id_eve',

                                    fieldCls: 'x-item-disabled',

                                    fieldStyle: 'color:#808080;',

                                    name: 'id_eve',

                                    readOnly: true,

                                    readOnlyCls: 'x-item-disabled',

                                    fieldLabel: 'Codigo',

                                    hideLabel: false,

                                    labelStyle: 'color:#808080;'

                                },

                                {

                                    xtype: 'textfield',

                                    anchor: '100%',

                                    id: 'nom_eve',

                                    name: 'nom_eve',

                                    fieldLabel: 'Nombre Evento',

                                    allowBlank: false,

                                    blankText: 'Debe ingresar un nombre para la Evento'

                                },
								{
                                    xtype: 'container',
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    items: [

                                        {
                                            xtype: 'datefield',
											id: 'fech_ini_eve',
											name: 'fech_ini_eve',
											vtype: 'daterange',
											endDateField: 'fech_fin_eve',
											fieldLabel: 'Fecha Inicio',
											blankText: 'Debe Ingresar una fecha de Inicio',
											allowBlank: false,
											width:220,
											format: 'd-m-Y'

                                        }
                                    ]
								},
                                {
									

                                    xtype: 'container',

                                    margin: '5 0 5 0',

                                    layout: {

                                        align: 'stretch',

                                        type: 'hbox'

                                    },

                                    items: [

                                        {

                                            xtype: 'datefield',

											id: 'fech_fin_eve',

											name: 'fech_fin_eve',

											vtype: 'daterange',

											starDateField: 'fech_ini_eve',

											fieldLabel: 'Fecha Final',

											blankText: 'Debe Ingresar una fecha de final',

											allowBlank: false,

											width:220,

											format: 'd-m-Y'

                                        }
                                    ]
                                },
                                {

                                    xtype: 'combobox',

                                    anchor: '100%',

                                    id: 'est_eve',

                                    name: 'est_eve',

                                    fieldLabel: 'Estado',

                                    allowBlank: false,

                                    blankText: 'Debe asignar un estado.',

                                    editable: false,

                                    autoSelect: false,

                                    displayField: 'value',

                                    forceSelection: true,

                                    queryMode: 'local',

                                    selectOnTab: false,

                                    store: 'estado_eve',

                                    typeAhead: true,

                                    valueField: 'est_eve'

                                }

                            ]

                        }

                    ]

                }

            ]

        });



        me.callParent(arguments);

    }


});