/*
 * File: app/view/MantenerPonencia.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('vision.view.MantenerPonencia', {
    extend: 'Ext.window.Window',

    requires: [
        'vision.view.override.MantenerPonencia'
    ],

    height: 530,
    id: 'winPonencia',
    width: 455,
    layout: {
        type: 'border'
    },
    title: 'Mantener Ponencia',
    animateTarget: 'btnManPone',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    border: 0,
                    id: 'formPon',
                    bodyPadding: 10,
                    url: '../../administracion/ponencia/registar_ponencia',
                    waitTitle: 'Guardando...',
                    items: [
                        {
                            xtype: 'fieldset',
                            title: 'Datos de Ponencia',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    cls: 'x-item-disabled',
                                    hidden: false,
                                    id: 'id_pon',
                                    fieldCls: 'x-item-disabled',
                                    fieldStyle: 'color:#808080;',
                                    name: 'id_pon',
                                    readOnly: true,
                                    readOnlyCls: 'x-item-disabled',
                                    fieldLabel: 'Codigo',
                                    hideLabel: false,
                                    labelStyle: 'color:#808080;'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'cod_eve_pon',
                                    width: 415,
                                    name: 'cod_eve_pon',
                                    fieldLabel: 'Evento',
                                    allowBlank: false,
                                    blankText: 'La Ponencia debe ser asignada a un evento.',
                                    editable: false,
                                    autoSelect: false,
                                    displayField: 'nom_eve',
                                    forceSelection: true,
                                    queryCaching: false,
                                    selectOnTab: false,
                                    store: 'eventoCombo',
                                    typeAhead: true,
                                    valueField: 'id_eve',
                                    valueNotFoundText: 'no se cargo la data'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    id: 'fech_ini_pon',
                                    name: 'fech_ini_pon',
                                    fieldLabel: 'Fecha Inicio',
                                    allowBlank: false,
                                    blankText: 'Debe Ingresar una fecha de Inicio',
                                    format: 'd-m-Y H:i:s'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    id: 'fech_fin_pon',
                                    name: 'fech_fin_pon',
                                    fieldLabel: 'Fecha Final',
                                    allowBlank: false,
                                    blankText: 'Debe Ingresar una fecha de final',
                                    format: 'd-m-Y H:i:s'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'nom_pon',
                                    name: 'nom_pon',
                                    fieldLabel: 'Nombre Ponencia',
                                    allowBlank: false,
                                    blankText: 'Debe ingresar un nombre para la Ponencia'
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    id: 'desc_pon',
                                    name: 'desc_pon',
                                    fieldLabel: 'Descripcion'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'tipo_pon',
                                    name: 'tipo_pon',
                                    fieldLabel: 'Tipo',
                                    editable: false,
                                    autoSelect: false,
                                    displayField: 'value',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    selectOnTab: false,
                                    store: 'tipo_pon',
                                    typeAhead: true,
                                    valueField: 'tipo_pon'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'dirigido_a_pon',
                                    name: 'dirigido_a_pon',
                                    fieldLabel: 'Dirigido a',
                                    editable: false,
                                    autoSelect: false,
                                    displayField: 'value',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    selectOnTab: false,
                                    store: 'Dirigido',
                                    typeAhead: true,
                                    valueField: 'id_dir'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'est_pon',
                                    name: 'est_pon',
                                    fieldLabel: 'Estado',
                                    allowBlank: false,
                                    blankText: 'Debe asignar un estado.',
                                    editable: false,
                                    autoSelect: false,
                                    displayField: 'value',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    selectOnTab: false,
                                    store: 'estado_pon',
                                    typeAhead: true,
                                    valueField: 'est_pon'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            title: 'Ambiente de Ponencia',
                            items: [
                                {
                                    xtype: 'container',
                                    margin: '1 1 1 1',
                                    layout: {
                                        columns: 2,
                                        type: 'table'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            id: 'id_amb_pon',
                                            width: 220,
                                            name: 'id_amb_pon',
                                            fieldLabel: 'Ambiente',
                                            labelWidth: 70,
                                            allowBlank: false,
                                            editable: false,
                                            autoSelect: false,
                                            displayField: 'value',
                                            queryMode: 'local',
                                            selectOnTab: false,
                                            store: 'ambiente',
                                            typeAhead: true,
                                            valueField: 'id_amb'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            margin: '0 0 0 20',
                                            width: 160,
                                            name: 'capac_amb',
                                            fieldLabel: 'Capacidad',
                                            labelWidth: 70
                                        },
                                        {
                                            xtype: 'combobox',
                                            width: 220,
                                            name: 'cod_fia_amb',
                                            fieldLabel: 'Aula',
                                            labelWidth: 70,
                                            allowBlank: false,
                                            autoSelect: false,
                                            displayField: 'value',
                                            queryMode: 'local',
                                            selectOnTab: false,
                                            store: 'Aula',
                                            typeAhead: true,
                                            valueField: 'cod_fia_amb'
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    listeners: {
                        actioncomplete: {
                            fn: me.onFormPonActioncomplete,
                            scope: me
                        },
                        actionfailed: {
                            fn: me.onFormPonActionfailed,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onFormPonActioncomplete: function(basicForm, action, options) {

        Ext.getCmp('winPonencia').close(); 
        Ext.getCmp('gridponencia').getStore().load();
        Ext.getCmp('gridponencia').getView().refresh();
    },

    onFormPonActionfailed: function(basicForm, action, options) {

    }

});