/*
 * File: app/view/MantenerExpositor.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('vision.view.MantenerExpositor', {
    extend: 'Ext.window.Window',

    requires: [
        'vision.view.override.MantenerExpositor'
    ],

    height: 367,
    id: 'winExpositor',
    width: 561,
    layout: {
        type: 'border'
    },
    title: 'Mantener Expositor',
    animateTarget: 'btnRegExpo',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    border: 0,
                    id: 'formExpositor',
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    bodyPadding: 10,
                    url: '../../administracion/expositor/registar_expositor',
                    waitTitle: 'Guardando...',
                    items: [
                        {
                            xtype: 'fieldset',
                            width: 327,
                            title: 'Datos de Expositor',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    cls: 'x-item-disabled',
                                    hidden: false,
                                    id: 'cod_exp',
                                    fieldCls: 'x-item-disabled',
                                    fieldStyle: 'color:#808080;',
                                    name: 'cod_exp',
                                    readOnly: true,
                                    readOnlyCls: 'x-item-disabled',
                                    fieldLabel: 'Codigo Expositor',
                                    hideLabel: false,
                                    labelStyle: 'color:#808080;',
                                    labelWidth: 125
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    id: 'tip_doc',
                                    name: 'tip_doc',
                                    fieldLabel: 'Tipo de Documento',
                                    labelWidth: 125,
                                    allowBlank: false,
                                    blankText: 'Debe asignar un estado.',
                                    editable: false,
                                    autoSelect: false,
                                    displayField: 'value',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    selectOnTab: false,
                                    store: 'tipo_documento',
                                    typeAhead: true,
                                    valueField: 'tip_doc'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'num_doc',
                                    name: 'num_doc',
                                    fieldLabel: 'Num. Documento',
                                    labelWidth: 125
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'nom_exp',
                                    name: 'nom_exp',
                                    fieldLabel: 'Nombre Expositor',
                                    labelWidth: 125,
                                    allowBlank: false,
                                    blankText: 'Debe ingresar un nombre para la Ponencia'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'ape_pat_exp',
                                    name: 'ape_pat_exp',
                                    fieldLabel: 'Apellido Paterno',
                                    labelWidth: 125
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'ape_mat_exp',
                                    name: 'ape_mat_exp',
                                    fieldLabel: 'Apellido Materno',
                                    labelWidth: 125
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'pais_exp',
                                    name: 'pais_exp',
                                    fieldLabel: 'Pais',
                                    labelWidth: 125
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'absolute'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    x: 30,
                                    y: 10,
                                    height: 200,
                                    width: 160
                                },
                                {
                                    xtype: 'filefield',
                                    x: 0,
                                    y: 250,
                                    margin: '0 0 0 10',
                                    fieldLabel: 'Label',
                                    hideLabel: true
                                }
                            ]
                        }
                    ],
                    listeners: {
                        actioncomplete: {
                            fn: me.onFormPonActioncomplete,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onFormPonActioncomplete: function(basicForm, action, options) {

        Ext.getCmp('winExpositor').hide(); 
        Ext.getCmp('gridExpositor').getStore().load();
        Ext.getCmp('gridExpositor').getView().refresh();
    }

});