/*
 * File: app/model/Cuotas.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('vision.model.Cuotas', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'NUM_CONTRATOPF'
        },
        {
            name: 'NUM_EMICUOTAPF'
        },
        {
            name: 'MTO_CUOTATOTPF'
        },
        {
            name: 'FEC_EMICUOTAVENC'
        },
        {
            name: 'COD_ASEGURATIT'
        },
        {
            name: 'DSC_TITULARAST'
        },
        {
            name: 'DSC_DIRECAST'
        },
        {
            name: 'NUM_TELEF1AST'
        },
        {
            name: 'DSC_DIDENTAST'
        }
    ]
});