/*

 * File: app/model/Ponencia.js

 *

 * This file was generated by Sencha Architect version 2.1.0.

 * http://www.sencha.com/products/architect/

 *

 * This file requires use of the Ext JS 4.1.x library, under independent license.

 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more

 * details see http://www.sencha.com/license or contact license@sencha.com.

 *

 * This file will be auto-generated each and everytime you save your project.

 *

 * Do NOT hand edit this file.

 */



Ext.define('vision.model.Ponencia', {

    extend: 'Ext.data.Model',



    fields: [

        {

            name: 'id_pon'

        },

        {

            name: 'fech_ini_pon'

        },

        {

            name: 'fech_fin_pon'

        },

        {

            name: 'nom_pon'

        },

        {

            name: 'desc_pon'

        },

        {

            name: 'tipo_pon'

        },

        {

            name: 'dirigido_a_pon'

        },

        {

            name: 'est_pon'

        },
		{

            name: 'est_pon_desc'

        },
        {

            name: 'duracion'

        },

        {

            name: 'nom_exp'

        },

        {

            name: 'tip_amb'

        },

        {

            name: 'cod_exp_pon'

        },

        {

            name: 'cod_eve_pon'

        },

        {

            name: 'id_amb_pon'

        },

        {

            name: 'id_req_pon'

        },

        {

            name: 'dir_desc'

        },

        {

            name: 'amb_des'

        },

        {

            name: 'capac_amb'

        },

        {

            name: 'cod_fia_amb'

        },

        {

            name: 'tip_pon_dsc'

        }

    ]

});