/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'Ponencia',
        'tipo_pon',
        'Expositor',
        'Ambiente',
        'Aula',
        'Evento'
    ],
    stores: [
        'Ponencia',
        'estado_pon',
        'ambiente',
        'Evento',
        'Dirigido',
        'tipo_pon',
        'Expositor',
        'Aula',
        'estado_eve',
        'eventoCombo',
        'tipo_documento'
    ],
    views: [
        'Main',
        'Contenedor',
        'PanelPrincipal',
        'MantenerPonencia',
        'GridEvento',
        'MantenerEvento',
        'GridExpositor',
        'MantenerExpositor'
    ],
    autoCreateViewport: true,
    name: 'vision',

    launch: function() {
        sessionStorage.setItem('id_pon',-1);
        sessionStorage.setItem('id_eve',-1);
        sessionStorage.setItem('cod_exp',-1);
        Ext.getCmp('userlabel').setText(sessionStorage.nomUser);

    }

});
