/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true,
});

Ext.application({
    models: [
        'MyModel',
        'tipo_pon'
    ],
    stores: [
        'MyJsonStore',
        'estado_pon',
        'ambiente',
        'Evento',
        'Dirigido',
        'tipo_pon'
    ],
    views: [
        'Main',
        'Contenedor',
        'PanelPrincipal',
        'MantenerPonencia'
    ],
    autoCreateViewport: true,
    name: 'vision',
    appFolder: '../../../application/app_admin/app',

    launch: function() {
        localStorage.setItem('id_pon',-1);
    }

});
